# 📊 What Makes a TV Series Popular?
### Student Data Lab (IMDb + Netflix + TMDb)

You will analyze real TV series data to discover what makes shows popular.

In [1]:
!make init
!python -m netflix.fetch
!python -m netflix.build

===============================================================================
Initializing local development environment. This will verify and set up your
Python virtual environment, install all 3rd-party package requirements.
This may take a few minutes...
===============================================================================


===============================================================================
Initialization complete!
===============================================================================
make python-init
===============================================================================
Initializing Python virtual environment and installing dependencies. This may take a few minutes...
===============================================================================
rm -r -f venv && \
	mkdir -p .pypi_cache && \
	make check-python

===============================================================================
Verifying that Python python3.13 is installed ...
===============================================================================

make python-clean && \
	npm install && \
	python3.13 -m venv venv && \
	source venv/bin/activate && \
	python3.13 -m pip install pip==25.3 setuptools wheel pip-tools && \
	PIP_CACHE_DIR=.pypi_cache python3.13 -m pip install -r requirements/local.txt

===============================================================================
Cleaning Python virtual environment and __pycache__ directories ...
===============================================================================

rm -rf venv
find ./netflix/ -name __pycache__ -type d -exec rm -rf {} +
⠙⠹⠸
up to date, audited 471 packages in 428ms
⠸
⠸101 packages are looking for funding
⠸  run `npm fund` for details
⠸
found 0 vulnerabilities
⠸Collecting pip==25.3
  Using cached pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Collecting setuptools
  Using cached setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting wheel
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting pip-tools
  Using cached pip_tools-7.5.3-py3-none-any.whl.metadata (27 kB)
Collecting packaging>=24.0 (from wheel)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting build>=1.0.0 (from pip-tools)
  Downloading build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Collecting click>=8 (from pip-tools)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting pyproject_hooks (from pip-tools)
  Using cached pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Using cached pip-25.3-py3-none-any.whl (1.8 MB)
Using cached setuptools-83.0.0-py3-none-any.whl (1.0 MB)
Using cached wheel-0.47.0-py3-none-any.whl (32 kB)
Using cached pip_tools-7.5.3-py3-none-any.whl (71 kB)
Downloading build-1.5.0-py3-none-any.whl (26 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Using cached pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: setuptools, pyproject_hooks, pip, packaging, click, wheel, build, pip-tools
  Attempting uninstall: pip━━━━━━━━━━━━━━━━━━━━━ 0/8 [setuptools]
    Found existing installation: pip 25.2━━━ 0/8 [setuptools]
    Uninstalling pip-25.2:m╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/8 [pip]
      Successfully uninstalled pip-25.2━━━━━━━━━━━━━━━━━━━━━━━ 2/8 [pip]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [pip-tools]/8 [click]
Successfully installed build-1.5.0 click-8.4.2 packaging-26.2 pip-25.3 pip-tools-7.5.3 pyproject_hooks-1.2.0 setuptools-83.0.0 wheel-0.47.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Collecting annotated-doc==0.0.4 (from -r requirements/local.txt (line 7))
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting anyio==4.13.0 (from -r requirements/local.txt (line 9))
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting appnope==0.1.4 (from -r requirements/local.txt (line 13))
  Using cached appnope-0.1.4-py2.py3-none-any.whl.metadata (908 bytes)
Collecting argon2-cffi==25.1.0 (from -r requirements/local.txt (line 15))
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting argon2-cffi-bindings==25.1.0 (from -r requirements/local.txt (line 17))
  Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting arrow==1.4.0 (from -r requirements/local.txt (line 19))
  Using cached arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Collecting ast-serialize==0.5.0 (from -r requirements/local.txt (line 21))
  Using cached ast_serialize-0.5.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (1.3 kB)
Collecting astroid==4.0.4 (from -r requirements/local.txt (line 23))
  Using cached astroid-4.0.4-py3-none-any.whl.metadata (4.4 kB)
Collecting asttokens==3.0.1 (from -r requirements/local.txt (line 25))
  Using cached asttokens-3.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting async-lru==2.3.0 (from -r requirements/local.txt (line 27))
  Using cached async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting attrs==26.1.0 (from -r requirements/local.txt (line 29))
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting babel==2.18.0 (from -r requirements/local.txt (line 33))
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting bandit==1.9.4 (from -r requirements/local.txt (line 35))
  Using cached bandit-1.9.4-py3-none-any.whl.metadata (7.1 kB)
Collecting beautifulsoup4==4.15.0 (from -r requirements/local.txt (line 37))
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting black==26.5.1 (from -r requirements/local.txt (line 41))
  Using cached black-26.5.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (95 kB)
Collecting bleach==6.4.0 (from bleach[css]==6.4.0->-r requirements/local.txt (line 43))
  Using cached bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: build==1.5.0 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 47)) (1.5.0)
Collecting cachetools==7.1.4 (from -r requirements/local.txt (line 49))
  Using cached cachetools-7.1.4-py3-none-any.whl.metadata (5.5 kB)
Collecting certifi==2026.5.20 (from -r requirements/local.txt (line 51))
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi==2.0.0 (from -r requirements/local.txt (line 56))
  Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.6 kB)
Collecting cfgv==3.5.0 (from -r requirements/local.txt (line 58))
  Using cached cfgv-3.5.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting charset-normalizer==3.4.7 (from -r requirements/local.txt (line 60))
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting click==8.4.1 (from -r requirements/local.txt (line 62))
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting cloudpickle==3.1.2 (from -r requirements/local.txt (line 66))
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting codespell==2.4.2 (from -r requirements/local.txt (line 68))
  Using cached codespell-2.4.2-py3-none-any.whl.metadata (15 kB)
Collecting colorama==0.4.6 (from -r requirements/local.txt (line 70))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting comm==0.2.3 (from -r requirements/local.txt (line 72))
  Using cached comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
Collecting contourpy==1.3.3 (from -r requirements/local.txt (line 74))
  Using cached contourpy-1.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting coverage==7.14.1 (from -r requirements/local.txt (line 76))
  Using cached coverage-7.14.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.6 kB)
Collecting cssselect==1.4.0 (from -r requirements/local.txt (line 78))
  Using cached cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Collecting cycler==0.12.1 (from -r requirements/local.txt (line 80))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting debugpy==1.8.21 (from -r requirements/local.txt (line 82))
  Using cached debugpy-1.8.21-cp313-cp313-macosx_15_0_universal2.whl.metadata (1.4 kB)
Collecting decorator==5.3.1 (from -r requirements/local.txt (line 84))
  Using cached decorator-5.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting defusedxml==0.7.1 (from -r requirements/local.txt (line 86))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting dill==0.4.1 (from -r requirements/local.txt (line 88))
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting distlib==0.4.3 (from -r requirements/local.txt (line 90))
  Using cached distlib-0.4.3-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting duckdb==1.5.3 (from -r requirements/local.txt (line 92))
  Using cached duckdb-1.5.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.2 kB)
Collecting executing==2.2.1 (from -r requirements/local.txt (line 94))
  Using cached executing-2.2.1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting fastjsonschema==2.21.2 (from -r requirements/local.txt (line 96))
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting filelock==3.29.4 (from -r requirements/local.txt (line 98))
  Using cached filelock-3.29.4-py3-none-any.whl.metadata (2.0 kB)
Collecting flake8==7.3.0 (from -r requirements/local.txt (line 103))
  Using cached flake8-7.3.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting flake8-coding==1.3.2 (from -r requirements/local.txt (line 107))
  Using cached flake8_coding-1.3.2-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting fonttools==4.63.0 (from -r requirements/local.txt (line 109))
  Using cached fonttools-4.63.0-cp313-cp313-macosx_10_13_universal2.whl.metadata (118 kB)
Collecting fqdn==1.5.1 (from -r requirements/local.txt (line 111))
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting h11==0.16.0 (from -r requirements/local.txt (line 113))
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting httpcore==1.0.9 (from -r requirements/local.txt (line 115))
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting httpx==0.28.1 (from -r requirements/local.txt (line 117))
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting identify==2.6.19 (from -r requirements/local.txt (line 119))
  Using cached identify-2.6.19-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting idna==3.18 (from -r requirements/local.txt (line 121))
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting iniconfig==2.3.0 (from -r requirements/local.txt (line 127))
  Using cached iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting ipykernel==7.3.0 (from -r requirements/local.txt (line 129))
  Using cached ipykernel-7.3.0-py3-none-any.whl.metadata (4.5 kB)
Collecting ipython==9.14.1 (from -r requirements/local.txt (line 133))
  Using cached ipython-9.14.1-py3-none-any.whl.metadata (4.7 kB)
Collecting ipython-pygments-lexers==1.1.1 (from -r requirements/local.txt (line 135))
  Using cached ipython_pygments_lexers-1.1.1-py3-none-any.whl.metadata (1.1 kB)
Collecting isoduration==20.11.0 (from -r requirements/local.txt (line 137))
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting isort==8.0.1 (from -r requirements/local.txt (line 139))
  Using cached isort-8.0.1-py3-none-any.whl.metadata (11 kB)
Collecting jedi==0.20.0 (from -r requirements/local.txt (line 141))
  Using cached jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Collecting jinja2==3.1.6 (from -r requirements/local.txt (line 143))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting joblib==1.5.3 (from -r requirements/local.txt (line 149))
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting json5==0.14.0 (from -r requirements/local.txt (line 151))
  Using cached json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonpointer==3.1.1 (from -r requirements/local.txt (line 153))
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting jsonschema==4.26.0 (from jsonschema[format-nongpl]==4.26.0->-r requirements/local.txt (line 155))
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting jsonschema-specifications==2025.9.1 (from -r requirements/local.txt (line 160))
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-client==8.9.1 (from -r requirements/local.txt (line 162))
  Using cached jupyter_client-8.9.1-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyter-core==5.9.1 (from -r requirements/local.txt (line 167))
  Using cached jupyter_core-5.9.1-py3-none-any.whl.metadata (1.5 kB)
Collecting jupyter-events==0.12.1 (from -r requirements/local.txt (line 176))
  Using cached jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-lsp==2.3.1 (from -r requirements/local.txt (line 178))
  Using cached jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server==2.19.0 (from -r requirements/local.txt (line 180))
  Using cached jupyter_server-2.19.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyter-server-terminals==0.5.4 (from -r requirements/local.txt (line 186))
  Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab==4.5.8 (from -r requirements/local.txt (line 188))
  Using cached jupyterlab-4.5.8-py3-none-any.whl.metadata (16 kB)
Collecting jupyterlab-pygments==0.3.0 (from -r requirements/local.txt (line 190))
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting jupyterlab-server==2.28.0 (from -r requirements/local.txt (line 192))
  Using cached jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupytext==1.19.3 (from -r requirements/local.txt (line 194))
  Using cached jupytext-1.19.3-py3-none-any.whl.metadata (15 kB)
Collecting kaggle==2.2.1 (from -r requirements/local.txt (line 196))
  Using cached kaggle-2.2.1-py3-none-any.whl.metadata (16 kB)
Collecting kagglesdk==0.1.30 (from -r requirements/local.txt (line 198))
  Using cached kagglesdk-0.1.30-py3-none-any.whl.metadata (13 kB)
Collecting kiwisolver==1.5.0 (from -r requirements/local.txt (line 200))
  Using cached kiwisolver-1.5.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.1 kB)
Collecting lark==1.3.1 (from -r requirements/local.txt (line 202))
  Using cached lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting librt==0.11.0 (from -r requirements/local.txt (line 204))
  Using cached librt-0.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (1.3 kB)
Collecting llvmlite==0.47.0 (from -r requirements/local.txt (line 206))
  Using cached llvmlite-0.47.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (5.0 kB)
Collecting markdown-it-py==4.2.0 (from -r requirements/local.txt (line 210))
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting markupsafe==3.0.3 (from -r requirements/local.txt (line 215))
  Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting matplotlib==3.11.0 (from -r requirements/local.txt (line 219))
  Using cached matplotlib-3.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (80 kB)
Collecting matplotlib-inline==0.2.2 (from -r requirements/local.txt (line 223))
  Using cached matplotlib_inline-0.2.2-py3-none-any.whl.metadata (2.4 kB)
Collecting mccabe==0.7.0 (from -r requirements/local.txt (line 227))
  Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting mdit-py-plugins==0.6.1 (from -r requirements/local.txt (line 231))
  Using cached mdit_py_plugins-0.6.1-py3-none-any.whl.metadata (2.9 kB)
Collecting mdurl==0.1.2 (from -r requirements/local.txt (line 233))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting mistune==3.2.1 (from -r requirements/local.txt (line 235))
  Using cached mistune-3.2.1-py3-none-any.whl.metadata (1.9 kB)
Collecting mypy==2.1.0 (from -r requirements/local.txt (line 237))
  Using cached mypy-2.1.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.3 kB)
Collecting mypy-extensions==1.1.0 (from -r requirements/local.txt (line 241))
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting narwhals==2.22.1 (from -r requirements/local.txt (line 246))
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting nbclient==0.11.0 (from -r requirements/local.txt (line 248))
  Using cached nbclient-0.11.0-py3-none-any.whl.metadata (7.3 kB)
Collecting nbconvert==7.17.1 (from -r requirements/local.txt (line 250))
  Using cached nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Collecting nbformat==5.10.4 (from -r requirements/local.txt (line 252))
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting nest-asyncio2==1.7.2 (from -r requirements/local.txt (line 258))
  Using cached nest_asyncio2-1.7.2-py3-none-any.whl.metadata (6.3 kB)
Collecting nodeenv==1.10.0 (from -r requirements/local.txt (line 260))
  Using cached nodeenv-1.10.0-py2.py3-none-any.whl.metadata (24 kB)
Collecting notebook-shim==0.2.4 (from -r requirements/local.txt (line 262))
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting numba==0.65.1 (from -r requirements/local.txt (line 264))
  Using cached numba-0.65.1-cp313-cp313-macosx_12_0_arm64.whl.metadata (2.9 kB)
Collecting numpy==2.4.6 (from -r requirements/local.txt (line 266))
  Using cached numpy-2.4.6-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: packaging==26.2 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 278)) (26.2)
Collecting pandas==2.3.3 (from -r requirements/local.txt (line 296))
  Using cached pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting pandas-stubs==3.0.3.260530 (from -r requirements/local.txt (line 301))
  Using cached pandas_stubs-3.0.3.260530-py3-none-any.whl.metadata (11 kB)
Collecting pandocfilters==1.5.1 (from -r requirements/local.txt (line 303))
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting parso==0.8.7 (from -r requirements/local.txt (line 305))
  Using cached parso-0.8.7-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting pathspec==1.1.1 (from -r requirements/local.txt (line 307))
  Using cached pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting pexpect==4.9.0 (from -r requirements/local.txt (line 311))
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pillow==12.2.0 (from -r requirements/local.txt (line 313))
  Using cached pillow-12.2.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.8 kB)
Requirement already satisfied: pip-tools==7.5.3 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 315)) (7.5.3)
Collecting platformdirs==4.10.0 (from -r requirements/local.txt (line 317))
  Using cached platformdirs-4.10.0-py3-none-any.whl.metadata (5.5 kB)
Collecting pluggy==1.6.0 (from -r requirements/local.txt (line 325))
  Using cached pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pre-commit==4.6.0 (from -r requirements/local.txt (line 329))
  Using cached pre_commit-4.6.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting prometheus-client==0.25.0 (from -r requirements/local.txt (line 331))
  Using cached prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting prompt-toolkit==3.0.52 (from -r requirements/local.txt (line 333))
  Using cached prompt_toolkit-3.0.52-py3-none-any.whl.metadata (6.4 kB)
Collecting protobuf==6.33.6 (from -r requirements/local.txt (line 335))
  Using cached protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Collecting psutil==7.2.2 (from -r requirements/local.txt (line 339))
  Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting ptyprocess==0.7.0 (from -r requirements/local.txt (line 343))
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)

In [2]:

import pandas as pd

imdb = pd.read_csv("netflix/data/imdb.titles.composite.csv")
netflix = pd.read_csv("netflix/data/netflix.titles.composite.csv")
tmdb = pd.read_csv("netflix/data/tmdb.titles.v3.csv")

print(imdb.shape, netflix.shape, tmdb.shape)

(299097, 15) (691, 13) (168639, 29)

## Exercise 1 — First Look at Popularity
Find the top shows in each dataset.

In [3]:

# Top Netflix shows by viewing hours
netflix.sort_values("netflix_viewing_hours", ascending=False).head(10)

,key,netflix_viewing_hours,netflix_weeks,netflix_year_hint,netflix_title,netflix_clean_title,tmdb_title,tmdb_popularity,tmdb_vote_average,tmdb_vote_count,imdb_title,imdb_averageRating,imdb_numVotes
661,st_th,2874260000,13,2022,Stranger Things,stranger things,Stranger Things,185.711,8.624,16161.0,Stranger Things,NaN,NaN
396,ga_sq,2289500000,20,2021,Squid Game,squid game,Squid Game,115.587,7.831,13053.0,Squid Game!,NaN,NaN
549,ma,1446260000,16,2021,Manifest,manifest,Manifest,111.411,7.728,1312.0,Manifest,NaN,NaN
447,he_mo,1170200000,14,2021,Money Heist,money heist,Money Heist,96.354,8.257,17836.0,Money Heist,8.2,612436.0
167,br,1108800000,11,2021,Bridgerton,bridgerton,Bridgerton,71.308,8.143,2045.0,Bridgerton,4.1,57.0
103,ar_ca_co,793740000,25,2022,Café con aroma de mujer,caf con aroma de mujer,Café con Aroma de Mujer,20.710,7.500,382.0,Café con aroma de mujer,8.6,106.0
690,yo,777480000,8,2021,You,you,続・アタッカーYOU 金メダルへの道,7.101,2.500,2.0,You,NaN,NaN
686,wi,757350000,6,2021,Windfall,windfall,Windfall,3.813,0.000,0.0,Windfall,NaN,NaN
607,oz,751600000,13,2022,Ozark,ozark,Ozark,68.006,8.244,1968.0,Ozark,8.4,394904.0
69,al_ar_us,659510000,11,2022,All of Us Are Dead,all of us are dead,All of Us Are Dead,107.108,8.354,3335.0,All of Us Are Dead,7.6,92709.0

In [4]:

# Top IMDb shows by rating
imdb.sort_values("averageRating", ascending=False).head(10)

,tconst,titleType,primaryTitle,originalTitle,startYear,endYear,runtimeMinutes,genres,title_key,averageRating,numVotes,all_akas,cast,directors,writers
113321,tt24228604,tvSeries,OdBita Pot,OdBita Pot,2022,2026,\N,Adventure,dita ot,9.8,1344.0,odbita pot,Anze Sever | Bit Sever,nm7689797,nm7689797
10372,tt41956044,tvSeries,D&D: Dungeon Masters,D&D: Dungeon Masters,2026,\N,\N,"Fantasy,Horror,Reality-TV",ungeon asters,9.8,115.0,d&d: dungeon masters,Mayanna Berrin | Devora Wilde | Neil Newbon | ...,nm0671741,\N
127839,tt28305644,tvSeries,EDP Watch,EDP Watch,2023,\N,\N,Crime,atch,9.7,106.0,edp watch,Alex Rosen | Skeeter Jean | Demarcus Cousins I...,nm15017595,nm15017595
263196,tt12831434,tvSeries,The Simonetta Lein Show,The Simonetta Lein Show,2020,2026,\N,Talk-Show,he imonetta ein how,9.7,810.0,the simonetta lein show,Gabriela Gonzalez | Kevin Harrington | Julian ...,\N,\N
164455,tt34929415,tvSeries,A Dog and a Plane,A Dog and a Plane,2026,\N,\N,"Comedy,Romance",og and a lane,9.7,551.0,a dog and a plane,Oabnithi Wiwattanawarang | Pompam Niti Chaichi...,nm8797158,\N
156259,tt33131139,tvSeries,Symposium,Symposium,2023,\N,\N,Talk-Show,ymposium,9.6,127.0,symposium,Niko Svanidze,nm16438483,nm16438483
59321,tt8088236,tvSeries,Geografens testamente,Geografens testamente,2011,2023,28,"Adventure,History",eografens testamente,9.6,1143.0,the geographers last will | geografens testamente,Judith Buchan | Lena Granhagen | Lakshman Mend...,nm1072502,"nm1072502,nm2050223,nm6813238"
63437,tt8560994,tvSeries,Friday Five Sharp,Friday Five Sharp,2015,\N,\N,Comedy,riday ive harp,9.6,4589.0,petak pet | friday five sharp,Kitodar Todorov | Tedi Dinh | Vladislav Petrov...,nm5663366,"nm5663366,nm11544010,nm1242398,nm9909867"
59344,tt8103440,tvSeries,Herne Katha,Herne Katha,2018,\N,\N,"Documentary,Short",erne atha,9.6,413.0,herne katha,Kamal Kumar | Bidhya Chapagain,"nm9678594,nm9678593","nm9678593,nm9678594"
36797,tt5961444,tvSeries,Upanishad Ganga,Upanishad Ganga,2012,2013,\N,"Drama,History,Short",panishad anga,9.6,1359.0,upanishad ganga,Rasika Dugal | Zakir Hussain | Sandeep Mohan |...,nm1363374,nm1363374

In [5]:

# Top TMDb shows by popularity
tmdb.sort_values("popularity", ascending=False).head(10)

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,overview,adult,backdrop_path,...,tagline,genres,created_by,languages,networks,origin_country,spoken_languages,production_companies,production_countries,episode_run_time
1771,63770,The Late Show with Stephen Colbert,9,1419,en,205,6.495,Stephen Colbert brings his signature satire an...,False,/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg,...,NaN,"Comedy, Talk","Jon Stewart, Stephen Colbert, Tom Purcell, Chr...",en,CBS,US,English,"Spartina Productions, CBS Studios",United States of America,41
3035,215803,Batang Quiapo,2,178,tl,99,7.030,A young man rises to be one of the biggest out...,False,/jIV5weV19wH02rnuWyMtYI4dYC8.jpg,...,NaN,"Action & Adventure, Comedy, Drama",NaN,tl,"TV5, Kapamilya Channel",PH,NaN,"ABS-CBN Entertainment, Dreamscape Entertainmen...",Philippines,0
2285,94722,Tagesschau,72,20839,de,145,7.500,"German daily news program, the oldest still ex...",False,/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg,...,NaN,News,NaN,de,ARD,DE,Deutsch,NDR,Germany,15
3593,14981,The Late Late Show with Craig Ferguson,11,2057,en,77,7.065,The Late Late Show with Craig Ferguson is an A...,False,/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg,...,NaN,"Comedy, Talk",NaN,en,CBS,US,English,NaN,United States of America,60
4565,2261,The Tonight Show Starring Johnny Carson,31,2924,en,51,7.800,The Tonight Show Starring Johnny Carson is a t...,False,/qFfWFwfaEHzDLWLuttWiYq7Poy2.jpg,...,NaN,Talk,"Steve Allen, Sylvester Weaver",en,NBC,US,English,"NBC Productions, Carson Productions",United States of America,60
4651,81329,Chronicles of the Sun,5,1252,fr,49,7.510,NaN,False,/rj3jBAZwPiOgkwAy1205MAgLahj.jpg,...,NaN,Soap,NaN,fr,France 2,FR,Français,"France Télévisions, Epeios Productions, France...",France,26
1600,59941,The Tonight Show Starring Jimmy Fallon,11,1233,en,234,6.038,After Jay Leno's second retirement from the pr...,False,/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg,...,Tonight's just getting started.,"Comedy, Talk",Jimmy Fallon,en,NBC,US,English,"Broadway Video, Universal Television, Electric...",United States of America,45
7314,244643,El amor no tiene receta,1,91,es,23,8.300,"Paz Roble, a kind, hard-working and honest wom...",False,/bIhmqQNXcyWRzH153d3jaCbLTy3.jpg,...,NaN,"Action & Adventure, Family, Drama, Soap, Comed...","Juan Osorio Ortiz, Pablo Ferrer García-Travesí...",es,"Univision, Las Estrellas, ViX","MX, US",Español,"TelevisaUnivision Mexico, Televisa",Mexico,50
8641,225660,Pira-Pirasong Paraiso,2,78,tl,17,7.000,A con artist takes on the job of pretending to...,False,/2N4LXvTkUwPRkbvyzdmzvtnCHgR.jpg,...,NaN,NaN,NaN,"en, tl","TV5, Kapamilya Channel",PH,English,Dreamscape Entertainment Television,Philippines,0
7217,91759,Come Home Love: Lo and Behold,1,2107,cn,23,4.565,"Hung Sue Gan starting from the bottom, establi...",False,/ohJTnu93hJ0Uonl86Wn3mOSlWXN.jpg,...,NaN,"Family, Comedy, Drama",NaN,cn,TVB Jade,HK,广州话 / 廣州話,TVB,Hong Kong,22

## Exercise 2 — What Does “Popular” Mean?
Compare different popularity signals.

In [6]:

netflix["netflix_viewing_hours"].describe()

count    6.910000e+02
mean     6.919165e+07
std      1.879555e+08
min      1.130000e+06
25%      8.930000e+06
50%      2.028000e+07
75%      5.560000e+07
max      2.874260e+09
Name: netflix_viewing_hours, dtype: float64

In [7]:

imdb["averageRating"].describe()

count    48167.000000
mean         6.851699
std          1.293658
min          1.000000
25%          6.300000
50%          7.100000
75%          7.700000
max          9.800000
Name: averageRating, dtype: float64

In [8]:

tmdb["popularity"].describe()

count    168639.000000
mean          5.882644
std          42.023216
min           0.000000
25%           0.600000
50%           0.857000
75%           2.431500
max        3707.008000
Name: popularity, dtype: float64

## Exercise 3 — High Views vs High Ratings

In [9]:

netflix.sort_values("netflix_viewing_hours", ascending=False).head(5)[["netflix_title","netflix_viewing_hours"]]

       netflix_title  netflix_viewing_hours
661  Stranger Things             2874260000
396       Squid Game             2289500000
549         Manifest             1446260000
447      Money Heist             1170200000
167       Bridgerton             1108800000

## Exercise 4 — Genre Power

In [10]:

imdb["genres"].dropna().head()

0    Crime,Drama
1    Documentary
2         Comedy
3     Reality-TV
4     Reality-TV
Name: genres, dtype: object

## Exercise 5 — Language & Global Reach

In [11]:

tmdb["original_language"].value_counts().head(10)

original_language
en    76304
zh    14422
ja    14048
ko     7820
de     7712
fr     7290
es     5602
pt     3551
ru     2963
nl     2923
Name: count, dtype: int64

## Exercise 6 — Short vs Long Shows

In [12]:

tmdb[["number_of_seasons","popularity"]].corr()

                   number_of_seasons  popularity
number_of_seasons           1.000000    0.189827
popularity                  0.189827    1.000000

## Exercise 7 — Binge Effect

In [13]:

netflix[["netflix_weeks","netflix_viewing_hours"]].corr()

                       netflix_weeks  netflix_viewing_hours
netflix_weeks               1.000000               0.634786
netflix_viewing_hours       0.634786               1.000000

## Exercise 8 — Cast Impact

In [14]:

imdb["cast_count"] = imdb["cast"].fillna("").apply(lambda x: len(x.split("|")))
imdb[["cast_count","averageRating"]].corr()

               cast_count  averageRating
cast_count        1.00000       -0.07716
averageRating    -0.07716        1.00000

## Exercise 9 — The Perfect Show Profile

Write your ideal show recipe using evidence from the dataset.

## Exercise 10 — Build a Hit Score

In [15]:

df = netflix.copy()

df["hit_score"] = (
    df["netflix_viewing_hours"] / df["netflix_viewing_hours"].max()
)

df.sort_values("hit_score", ascending=False).head(10)

,key,netflix_viewing_hours,netflix_weeks,netflix_year_hint,netflix_title,netflix_clean_title,tmdb_title,tmdb_popularity,tmdb_vote_average,tmdb_vote_count,imdb_title,imdb_averageRating,imdb_numVotes,hit_score
661,st_th,2874260000,13,2022,Stranger Things,stranger things,Stranger Things,185.711,8.624,16161.0,Stranger Things,NaN,NaN,1.000000
396,ga_sq,2289500000,20,2021,Squid Game,squid game,Squid Game,115.587,7.831,13053.0,Squid Game!,NaN,NaN,0.796553
549,ma,1446260000,16,2021,Manifest,manifest,Manifest,111.411,7.728,1312.0,Manifest,NaN,NaN,0.503176
447,he_mo,1170200000,14,2021,Money Heist,money heist,Money Heist,96.354,8.257,17836.0,Money Heist,8.2,612436.0,0.407131
167,br,1108800000,11,2021,Bridgerton,bridgerton,Bridgerton,71.308,8.143,2045.0,Bridgerton,4.1,57.0,0.385769
103,ar_ca_co,793740000,25,2022,Café con aroma de mujer,caf con aroma de mujer,Café con Aroma de Mujer,20.710,7.500,382.0,Café con aroma de mujer,8.6,106.0,0.276155
690,yo,777480000,8,2021,You,you,続・アタッカーYOU 金メダルへの道,7.101,2.500,2.0,You,NaN,NaN,0.270497
686,wi,757350000,6,2021,Windfall,windfall,Windfall,3.813,0.000,0.0,Windfall,NaN,NaN,0.263494
607,oz,751600000,13,2022,Ozark,ozark,Ozark,68.006,8.244,1968.0,Ozark,8.4,394904.0,0.261493
69,al_ar_us,659510000,11,2022,All of Us Are Dead,all of us are dead,All of Us Are Dead,107.108,8.354,3335.0,All of Us Are Dead,7.6,92709.0,0.229454

## Bonus — Polti's 36 Dramatic Situations
Choose ONE situation from Polti's framework and design a TV series around it.

Explain how it could become a hit using dataset evidence.

## our analysis
口碑分數以及觀看時數關係

## our analysisy
資料表屬性總表

In [34]:
import pandas as pd

# 1. 載入你本地最原始的 composite 與 v3 資料集
# （這三個是你在前面步驟中讀取過的原始 DataFrame）
print("=" * 80)
print("🔍 原始資料集維度（Columns）與欄位身家調查")
print("=" * 80)

# ------------------------------------------
# A. Netflix 複合資料集 (包含已匹配的 IMDb 資訊)
# ------------------------------------------
print(f"\n📌 1. Netflix 複合資料表 (netflix.titles.composite) — 共 {netflix.shape[0]} 列, {netflix.shape[1]} 個欄位")
print("-" * 80)
# 建立一個清晰的欄位結構表
netflix_info = pd.DataFrame({
    "資料型態": netflix.dtypes,
    "非空值數量": netflix.notna().sum(),
    "缺失值數量": netflix.isna().sum(),
    "缺失值比例": (netflix.isna().mean() * 100).round(2).astype(str) + "%",
    "數值範例": netflix.iloc[0].values
})
display(netflix_info)

# ------------------------------------------
# B. TMDb 原始資料集 (tmdb.titles.v3)
# ------------------------------------------
print(f"\n📌 2. TMDb 原始資料表 (tmdb.titles.v3) — 共 {tmdb.shape[0]} 列, {tmdb.shape[1]} 個欄位")
print("-" * 80)
tmdb_info = pd.DataFrame({
    "資料型態": tmdb.dtypes,
    "非空值數量": tmdb.notna().sum(),
    "缺失值數量": tmdb.isna().sum(),
    "缺失值比例": (tmdb.isna().mean() * 100).round(2).astype(str) + "%",
    "數值範例": tmdb.iloc[0].values
})
display(tmdb_info)

# ------------------------------------------
# C. IMDb 原始資料集 (imdb.titles.composite)
# ------------------------------------------
print(f"\n📌 3. IMDb 原始資料表 (imdb.titles.composite) — 共 {imdb.shape[0]} 列, {imdb.shape[1]} 個欄位")
print("-" * 80)
imdb_info = pd.DataFrame({
    "資料型態": imdb.dtypes,
    "非空值數量": imdb.notna().sum(),
    "缺失值數量": imdb.isna().sum(),
    "缺失值比例": (imdb.isna().mean() * 100).round(2).astype(str) + "%",
    "數值範例": imdb.iloc[0].values
})
display(imdb_info)

================================================================================
🔍 原始資料集維度（Columns）與欄位身家調查
================================================================================

📌 1. Netflix 複合資料表 (netflix.titles.composite) — 共 691 列, 13 個欄位
--------------------------------------------------------------------------------

                          資料型態  非空值數量  缺失值數量   缺失值比例      數值範例
key                     object    691      0    0.0%        10
netflix_viewing_hours    int64    691      0    0.0%  26580000
netflix_weeks            int64    691      0    0.0%         2
netflix_year_hint        int64    691      0    0.0%      2021
netflix_title           object    691      0    0.0%   The 100
netflix_clean_title     object    690      1   0.14%   the 100
tmdb_title              object    394    297  42.98%   The 100
tmdb_popularity        float64    394    297  42.98%   127.224
tmdb_vote_average      float64    394    297  42.98%     7.916
tmdb_vote_count        float64    394    297  42.98%    7666.0
imdb_title              object    664     27   3.91%   The 100
imdb_averageRating     float64    463    228   33.0%       9.4
imdb_numVotes          float64    463    228   33.0%      12.0

📌 2. TMDb 原始資料表 (tmdb.titles.v3) — 共 168639 列, 29 個欄位
--------------------------------------------------------------------------------

,資料型態,非空值數量,缺失值數量,缺失值比例,數值範例
id,int64,168639,0,0.0%,1399
name,object,168634,5,0.0%,Game of Thrones
number_of_seasons,int64,168639,0,0.0%,8
number_of_episodes,int64,168639,0,0.0%,73
original_language,object,168639,0,0.0%,en
vote_count,int64,168639,0,0.0%,21857
vote_average,float64,168639,0,0.0%,8.442
overview,object,93333,75306,44.66%,Seven noble families fight for control of the ...
adult,bool,168639,0,0.0%,False
backdrop_path,object,77780,90859,53.88%,/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg
first_air_date,object,136903,31736,18.82%,2011-04-17
last_air_date,object,138735,29904,17.73%,2019-05-19
homepage,object,50998,117641,69.76%,http://www.hbo.com/game-of-thrones
in_production,bool,168639,0,0.0%,False
original_name,object,168634,5,0.0%,Game of Thrones
popularity,float64,168639,0,0.0%,1083.917
poster_path,object,108737,59902,35.52%,/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg
type,object,168639,0,0.0%,Scripted
status,object,168639,0,0.0%,Ended
tagline,object,5330,163309,96.84%,Winter Is Coming
genres,object,99713,68926,40.87%,"Sci-Fi & Fantasy, Drama, Action & Adventure"
created_by,object,36496,132143,78.36%,"David Benioff, D.B. Weiss"
languages,object,110050,58589,34.74%,en
networks,object,97589,71050,42.13%,HBO
origin_country,object,137609,31030,18.4%,US
spoken_languages,object,109280,59359,35.2%,English
production_companies,object,59342,109297,64.81%,"Revolution Sun Studios, Television 360, Genera..."
production_countries,object,77511,91128,54.04%,"United Kingdom, United States of America"
episode_run_time,int64,168639,0,0.0%,0

📌 3. IMDb 原始資料表 (imdb.titles.composite) — 共 299097 列, 16 個欄位
--------------------------------------------------------------------------------

,資料型態,非空值數量,缺失值數量,缺失值比例,數值範例
tconst,object,299097,0,0.0%,tt38876090
titleType,object,299097,0,0.0%,tvSeries
primaryTitle,object,299096,1,0.0%,Gomorrah: The Origins
originalTitle,object,299096,1,0.0%,Gomorra: Le origini
startYear,object,299097,0,0.0%,2026
endYear,object,299097,0,0.0%,\N
runtimeMinutes,object,299097,0,0.0%,\N
genres,object,299097,0,0.0%,"Crime,Drama"
title_key,object,298121,976,0.33%,omorrah he rigins
averageRating,float64,48167,250930,83.9%,7.2
numVotes,float64,48167,250930,83.9%,1019.0
all_akas,object,299043,54,0.02%,gomorra: le origini | gomorrah: a kezdetek | g...
cast,object,255241,43856,14.66%,Flavio Furno | Biagio Forestieri | Luca Lubran...
directors,object,299097,0,0.0%,"nm3634704,nm4574756"
writers,object,299097,0,0.0%,"nm0006938,nm1288339,nm2500207"
cast_count,int64,299097,0,0.0%,13

## our analysis

TMDb 評分門檻： 必須大於或等於全體有評分影劇的 前 $50\%$（中位數 Median）。

TMDb 投票人數門檻： 必須大於或等於全體有投票人數的 前 $50\%$（中位數 Median），確保口碑具備大眾基數。串流觀看量門檻： 

觀看時數（netflix_viewing_hours）必須大於全體影劇的 平均值（Mean），確保在 Netflix 上確實引爆流量。

In [51]:
import pandas as pd

# 1. 讀取 Netflix 複合資料集
df = pd.read_csv("netflix/data/netflix.titles.composite.csv")

# 2. 排除沒有配對到 TMDb 或沒有評分數據的影劇，以計算乾淨的 P50 門檻
df_valid_tmdb = df.dropna(subset=["tmdb_vote_average", "tmdb_vote_count"])

# 3. 計算三大核心指標的篩選門檻
tmdb_rating_p50 = df_valid_tmdb["tmdb_vote_average"].median()  # TMDb 評分前 50% (中位數)
tmdb_votes_p50 = df_valid_tmdb["tmdb_vote_count"].median()    # TMDb 投票數前 50% (中位數)
netflix_hours_mean = df["netflix_viewing_hours"].mean()       # Netflix 觀看時數平均值

# 4. 套用三重條件進行「The Hit」篩選
hit_condition = (
    (df["tmdb_vote_average"] >= tmdb_rating_p50) &
    (df["tmdb_vote_count"] >= tmdb_votes_p50) &
    (df["netflix_viewing_hours"] > netflix_hours_mean)
)

df_hits = df[hit_condition].copy()

# 5. 數據單位轉換
df_hits["netflix_viewing_hours_million"] = (df_hits["netflix_viewing_hours"] / 1000000).round(2)

# 6. 依觀看時數由高到低（降冪）排序
df_hits_sorted = df_hits.sort_values(by="netflix_viewing_hours", ascending=False).reset_index(drop=True)

# 7. 顯示設定優化：強制 Pandas 展開所有 Rows 與 Columns，不出現任何「...」
pd.set_option('display.max_rows', None)        # 不省略任何列 (Rows)
pd.set_option('display.max_columns', None)     # 不省略任何欄 (Columns)
pd.set_option('display.width', 1000)           # 避免寬度不夠自動換行

# 選擇要展示的欄位，並將欄位改為中文名稱
display_cols = {
    "netflix_title": "影劇名稱",
    "tmdb_vote_average": "TMDb 評分",
    "tmdb_vote_count": "TMDb 投票數",
    "netflix_viewing_hours_million": "觀看時數 (百萬小時)",
    "netflix_weeks": "上榜週數"
}

# 8. 印出篩選報告與完整清單
print("=" * 80)
print("⚙️  【The Hit】黃金篩選門檻定義：")
print("-" * 80)
print(f"▸ 1. TMDb 評分門檻 (前 50% 中位數)  >= {tmdb_rating_p50:.2f} 分")
print(f"▸ 2. TMDb 投票數門檻 (前 50% 中位數)>= {int(tmdb_votes_p50)} 票")
print(f"▸ 3. Netflix 觀看時數門檻 (全體平均) >  {netflix_hours_mean / 1000000:.2f} 百萬小時")
print("=" * 80)
print(f"🎉 篩選完成！在 {len(df)} 部影劇中，共有 {len(df_hits_sorted)} 部完全符合條件：")
print("=" * 80)

# 直接呼叫與顯示 DataFrame (在 Jupyter 中會渲染成精美的無省略 HTML 表格)
display(df_hits_sorted[list(display_cols.keys())].rename(columns=display_cols))

================================================================================
⚙️  【The Hit】黃金篩選門檻定義：
--------------------------------------------------------------------------------
▸ 1. TMDb 評分門檻 (前 50% 中位數)  >= 6.96 分
▸ 2. TMDb 投票數門檻 (前 50% 中位數)>= 25 票
▸ 3. Netflix 觀看時數門檻 (全體平均) >  69.19 百萬小時
================================================================================
🎉 篩選完成！在 691 部影劇中，共有 71 部完全符合條件：
================================================================================

                                         影劇名稱  TMDb 評分  TMDb 投票數  觀看時數 (百萬小時)  上榜週數
0                             Stranger Things    8.624   16161.0      2874.26    13
1                                  Squid Game    7.831   13053.0      2289.50    20
2                                    Manifest    7.728    1312.0      1446.26    16
3                                 Money Heist    8.257   17836.0      1170.20    14
4                                  Bridgerton    8.143    2045.0      1108.80    11
5                     Café con aroma de mujer    7.500     382.0       793.74    25
6                                       Ozark    8.244    1968.0       751.60    13
7                          All of Us Are Dead    8.354    3335.0       659.51    11
8                                Virgin River    8.032     448.0       624.25     6
9                               Sex Education    8.304    6647.0       561.36     6
10                          The Queen of Flow    7.983    1391.0       561.23    16
11                       The Umbrella Academy    8.604    8891.0       414.63     5
12                 Extraordinary Attorney Woo    8.482     585.0       404.03     7
13                                  Cobra Kai    8.220    5734.0       383.64     4
14                             Emily in Paris    7.775    1152.0       341.63     5
15                                      Elite    8.071    8817.0       329.29     5
16                         The Lincoln Lawyer    7.806     183.0       305.27     6
17                       Hometown Cha-Cha-Cha    8.233     442.0       300.58    16
18                          Never Have I Ever    8.161    1557.0       297.78     4
19                                   Sex/Life    7.138    1200.0       282.10     7
20                          Business Proposal    8.422     281.0       279.11    13
21                                Locke & Key    7.903    1104.0       278.38     5
22                                The Sandman    8.064    1726.0       274.22     3
23                           The Marked Heart    7.817     232.0       272.75     7
24                          Vikings: Valhalla    7.851     671.0       265.55     5
25                              Love Is Blind    7.100      54.0       256.89     5
26                                Dark Desire    7.300    4181.0       202.94     5
27                                     Hustle    7.708     137.0       198.31     6
28                                    My Name    8.283     715.0       194.14     5
29                           The Last Kingdom    8.290    1485.0       189.57     5
30                             Peaky Blinders    8.546    8836.0       185.34     5
31                              Lost in Space    7.115      96.0       185.18     4
32                                     Carter    7.400      30.0       183.04    10
33                            Sweet Magnolias    7.800     206.0       182.94     5
34                               All American    8.245     414.0       180.66     5
35                            The Five Juanas    7.419     246.0       177.85     6
36                                       Alba    7.000     167.0       175.64     6
37                               Raising Dion    7.696     388.0       172.87     4
38                     Twenty Five Twenty One    8.597      98.0       171.61    10
39                       Anatomy of a Scandal    7.071     120.0       171.02     5
40                        Pasión de Gavilanes    7.641    1925.0       164.18     5
41                                  Collision    7.300      26.0       161.63     5
42                             Selling Sunset    7.100      39.0       158.78     4
43                                     Arcane    8.740    3341.0       154.27     6
44                                 Good Girls    7.998     509.0       153.14     6
45                           Who Killed Sara?    7.638    1132.0       143.61     4
46                              Midnight Mass    7.525     664.0       142.28     4
47                            Welcome to Eden    7.090     233.0       140.34     5
48                             Narcos: Mexico    7.939    1160.0       138.98     4
49                       The King's Affection    8.351     232.0       138.54    10
50                           Juvenile Justice    7.947      85.0       134.56     7
51                                 Archive 81    7.219     442.0       129.47     3
52                         Our Beloved Summer    8.500      74.0       128.89     8
53                           Alchemy of Souls    8.622     411.0       127.69     8
54                            The Good Doctor    8.503   11768.0       112.58     6
55                 The Snitch Cartel: Origins    7.885     283.0       112.14     6
56                                   Sintonia    8.200     179.0       109.43     2
57                                  Our Blues    8.800      43.0       105.15     9
58                                 First Kill    7.952     270.0       104.61     3
59                           The Chestnut Man    7.584     455.0       104.21     5
60               Forecasting Love and Weather    7.631      61.0       100.85     8
61   Money Heist: Korea - Joint Economic Area    7.900     601.0        98.37     3
62                                 True Story    7.171      82.0        90.82     3
63                                  Control Z    8.227    2242.0        89.83     3
64                             The Silent Sea    7.800     527.0        89.77     3
65                               Another Self    7.400      30.0        88.59     4
66                                On My Block    8.461     618.0        80.88     2
67  Turning Point: 9/11 and the War on Terror    7.287      83.0        80.68     3
68     The Seven Deadly Sins: Cursed by Light    8.462    4710.0        79.51     4
69                          Hospital Playlist    8.490     100.0        72.06     7
70                              I Am Georgina    7.111     293.0        71.29     3

## our analysis
？？

In [ ]:
import pandas as pd

# 1. 讀取資料集 (請確保此路徑與你之前的步驟一致)
df = pd.read_csv("netflix/data/netflix.titles.composite.csv")

# 2. 計算篩選門檻 (TMDb 評分前 50%, TMDb 投票數前 50%, 觀看時數大於平均值)
df_valid_tmdb = df.dropna(subset=["tmdb_vote_average", "tmdb_vote_count"])

tmdb_rating_p50 = df_valid_tmdb["tmdb_vote_average"].median()
tmdb_votes_p50 = df_valid_tmdb["tmdb_vote_count"].median()
netflix_hours_mean = df["netflix_viewing_hours"].mean()

# 3. 篩選出這 71 部 The Hit 影集
hit_condition = (
    (df["tmdb_vote_average"] >= tmdb_rating_p50) &
    (df["tmdb_vote_count"] >= tmdb_votes_p50) &
    (df["netflix_viewing_hours"] > netflix_hours_mean)
)
df_hits = df[hit_condition].copy()

# 4. 關鍵設定：強制 Pandas 展開所有欄位與資料，絕不使用 "..." 省略
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

print("=" * 80)
print(f"📊 【The Hit】篩選結果：共找到 {len(df_hits)} 部影集")
print("=" * 80)

# ─── 步驟 A：輸出這 71 部影集擁有的「所有屬性（欄位）總表」 ───
print("\n🔎 【屬性總表 (Attributes Schema)】")
print("-" * 80)

# 建立屬性分析表
schema_df = pd.DataFrame({
    "資料型態 (Dtype)": df_hits.dtypes,
    "非空值數量 (Non-Null)": df_hits.notnull().sum(),
    "缺失值數量 (Null)": df_hits.isnull().sum(),
    "缺失值比例 (%)": (df_hits.isnull().sum() / len(df_hits) * 100).round(2).astype(str) + "%"
})
display(schema_df)

# ─── 步驟 B：完整展示這 71 部影集的所有欄位數據（不省略） ───
print("\n🎬 【這 71 部影集的所有屬性完整資料】 (依觀看時數降冪排序)")
print("-" * 80)

# 將觀看時數降冪排序，並在 Jupyter 中渲染成完整的 HTML 表格
df_hits_sorted = df_hits.sort_values(by="netflix_viewing_hours", ascending=False).reset_index(drop=True)
display(df_hits_sorted)

================================================================================
📊 【The Hit】篩選結果：共找到 71 部影集
================================================================================

🔎 【屬性總表 (Attributes Schema)】
--------------------------------------------------------------------------------

                      資料型態 (Dtype)  非空值數量 (Non-Null)  缺失值數量 (Null) 缺失值比例 (%)
key                         object                71             0      0.0%
netflix_viewing_hours        int64                71             0      0.0%
netflix_weeks                int64                71             0      0.0%
netflix_year_hint            int64                71             0      0.0%
netflix_title               object                71             0      0.0%
netflix_clean_title         object                71             0      0.0%
tmdb_title                  object                71             0      0.0%
tmdb_popularity            float64                71             0      0.0%
tmdb_vote_average          float64                71             0      0.0%
tmdb_vote_count            float64                71             0      0.0%
imdb_title                  object                71             0      0.0%
imdb_averageRating         float64                47            24     33.8%
imdb_numVotes              float64                47            24     33.8%

🎬 【這 71 部影集的所有屬性完整資料】 (依觀看時數降冪排序)
--------------------------------------------------------------------------------

         key  netflix_viewing_hours  netflix_weeks  netflix_year_hint                              netflix_title                    netflix_clean_title                                 tmdb_title  tmdb_popularity  tmdb_vote_average  tmdb_vote_count                                 imdb_title  imdb_averageRating  imdb_numVotes
0      st_th             2874260000             13               2022                            Stranger Things                        stranger things                            Stranger Things          185.711              8.624          16161.0                            Stranger Things                 NaN            NaN
1      ga_sq             2289500000             20               2021                                 Squid Game                             squid game                                 Squid Game          115.587              7.831          13053.0                                Squid Game!                 NaN            NaN
2         ma             1446260000             16               2021                                   Manifest                               manifest                                   Manifest          111.411              7.728           1312.0                                   Manifest                 NaN            NaN
3      he_mo             1170200000             14               2021                                Money Heist                            money heist                                Money Heist           96.354              8.257          17836.0                                Money Heist                 8.2       612436.0
4         br             1108800000             11               2021                                 Bridgerton                             bridgerton                                 Bridgerton           71.308              8.143           2045.0                                 Bridgerton                 4.1           57.0
5   ar_ca_co              793740000             25               2022                    Café con aroma de mujer                 caf con aroma de mujer                    Café con Aroma de Mujer           20.710              7.500            382.0                    Café con aroma de mujer                 8.6          106.0
6         oz              751600000             13               2022                                      Ozark                                  ozark                                      Ozark           68.006              8.244           1968.0                                      Ozark                 8.4       394904.0
7   al_ar_us              659510000             11               2022                         All of Us Are Dead                     all of us are dead                         All of Us Are Dead          107.108              8.354           3335.0                         All of Us Are Dead                 7.6        92709.0
8      ri_vi              624250000              6               2021                               Virgin River                           virgin river                               Virgin River           54.192              8.032            448.0                               Virgin River                 7.4        60100.0
9      ed_se              561360000              6               2021                              Sex Education                          sex education                              Sex Education         1008.977              8.304           6647.0                              Sex Education                 7.2           25.0
10     fl_qu              561230000             16               2021                          The Queen of Flow                      the queen of flow                          The Queen of Flow          129.323              7.983           1391.0                          The Queen of Flow                 7.5         2076.0
11     ac_um              414630000              5               2022                       The Umbrella Academy                   the umbrella academy                       The Umbrella Academy           51.859              8.604           8891.0                       The Umbrella Academy                 7.0           74.0
12  at_ex_wo              404030000              7               2022                 Extraordinary Attorney Woo             extraordinary attorney woo                 Extraordinary Attorney Woo           42.923              8.482            585.0                 Extraordinary Attorney Woo                 8.5        38985.0
13     co_ka              383640000              4               2022                                  Cobra Kai                              cobra kai                                  Cobra Kai          118.256              8.220           5734.0                                  Cobra Kai                 6.9           36.0
14     em_pa              341630000              5               2021                             Emily in Paris                         emily in paris                             Emily in Paris           33.659              7.775           1152.0                             Emily in Paris                 6.8       143411.0
15        el              329290000              5               2021                                      Elite                                  elite                                      Elite          100.711              8.071           8817.0                                      Elite                 8.4          112.0
16     la_li              305270000              6               2022                         The Lincoln Lawyer                     the lincoln lawyer                         The Lincoln Lawyer           52.395              7.806            183.0                         The Lincoln Lawyer                 NaN            NaN
17  ch_ch_ho              300580000             16               2021                       Hometown Cha-Cha-Cha                   hometown cha cha cha                       Hometown Cha-Cha-Cha           35.367              8.233            442.0                       Hometown Cha-Cha-Cha                 8.3        29770.0
18   ha_i_ne              297780000              4               2021                          Never Have I Ever                      never have i ever                          Never Have I Ever           80.546              8.161           1557.0                          Never Have I Ever                 NaN            NaN
19     li_se              282100000              7               2021                                   Sex/Life                               sex life                                   Sex/Life          124.145              7.138           1200.0                                   Sex Life                 NaN            NaN
20     bu_pr              279110000             13               2022                          Business Proposal                      business proposal                          Business Proposal           88.533              8.422            281.0                          Business Proposal                 NaN            NaN
21     ke_lo              278380000              5               2021                                Locke & Key                              locke key                                Locke & Key           27.017              7.903           1104.0                                  Locke&Key                 NaN            NaN
22        sa              274220000              3               2022                                The Sandman                            the sandman                                The Sandman           64.168              8.064           1726.0                                The Sandman                 5.2            5.0
23     he_ma              272750000              7               2022                           The Marked Heart                       the marked heart                           The Marked Heart           35.526              7.817            232.0                           The Marked Heart                 6.6         4799.0
24     va_vi              265550000              5               2022                          Vikings: Valhalla                       vikings valhalla                          Vikings: Valhalla           59.232              7.851            671.0                          Vikings: Valhalla                 7.4        71704.0
25  bl_is_lo              256890000              5               2021                              Love Is Blind                          love is blind                              Love Is Blind           46.558              7.100             54.0                              Love is Blind                 NaN            NaN
26     da_de              202940000              5               2022                                Dark Desire                            dark desire                                Dark Desire           90.553              7.300           4181.0                                Dark Desire                 8.0           11.0
27        hu              198310000              6               2022                                     Hustle                                 hustle                                     Hustle           30.738              7.708            137.0                                     Hustle                 NaN            NaN
28     my_na              194140000              5               2021                                    My Name                                my name                                    My Name           25.525              8.283            715.0                                    My Name                 7.8        45026.0
29     ki_la              189570000              5               2022                           The Last Kingdom                       the last kingdom                           The Last Kingdom          143.794              8.290           1485.0                           The Last Kingdom                 8.4           13.0
30     bl_pe              185340000              5               2022                             Peaky Blinders                         peaky blinders                             Peaky Blinders          344.477              8.546           8836.0                             Peaky Blinders                 8.7       783155.0
31     lo_sp              185180000              4               2021                              Lost in Space                          lost in space                              Lost in Space          412.031              7.115             96.0                              Lost in Space                 NaN            NaN
32        ca              183040000             10               2021                                     Carter                                 carter                                     Carter           11.552              7.400             30.0                                     Carter                 NaN            NaN
33     ma_sw              182940000              5               2022                            Sweet Magnolias                        sweet magnolias                            Sweet Magnolias           25.831              7.800            206.0                            Sweet Magnolias                 7.3        28500.0
34     al_am              180660000              5               2021                               All American                           all american                               All American          140.694              8.245            414.0                               All American                 NaN            NaN
35     fi_ju              177850000              6               2021                            The Five Juanas                        the five juanas                            The Five Juanas           18.672              7.419            246.0                            The Five Juanas                 6.9         2615.0
36        al              175640000              6               2022                                       Alba                                   alba                                       Alba           12.840              7.000            167.0                                       Alba                 NaN            NaN
37     di_ra              172870000              4               2022                               Raising Dion                           raising dion                               Raising Dion           19.093              7.696            388.0                               Raising Dion                 8.1           83.0
38  fi_tw_tw              171610000             10               2022                     Twenty Five Twenty One                 twenty five twenty one                     Twenty Five Twenty One           31.730              8.597             98.0                     Twenty Five Twenty One                 8.6        22729.0
39     an_sc              171020000              5               2022                       Anatomy of a Scandal                   anatomy of a scandal                       Anatomy of a Scandal           13.197              7.071            120.0                       Anatomy of a Scandal                 7.0        40449.0
40   de_n_pa              164180000              5               2022                        Pasión de Gavilanes                    pasi n de gavilanes                        Pasión de Gavilanes          283.197              7.641           1925.0                           Pasión de sangre                 NaN            NaN
41        co              161630000              5               2021                                  Collision                              collision                                  Collision            5.795              7.300             26.0                                  Collision                 NaN            NaN
42     se_su              158780000              4               2021                             Selling Sunset                         selling sunset                             Selling Sunset            9.459              7.100             39.0                             Selling Sunset                 6.5         9335.0
43        ar              154270000              6               2021                                     Arcane                                 arcane                                     Arcane           42.447              8.740           3341.0                                     Arcane                 NaN            NaN
44     gi_go              153140000              6               2021                                 Good Girls                             good girls                                 Good Girls           52.352              7.998            509.0                                 Good Girls                 8.2          668.0
45  ki_sa_wh              143610000              4               2022                           Who Killed Sara?                        who killed sara                           Who Killed Sara?           18.157              7.638           1132.0                           Who Killed Sara?                 6.4        17647.0
46     ma_mi              142280000              4               2021                              Midnight Mass                          midnight mass                              Midnight Mass           21.999              7.525            664.0                              Midnight Mass                 7.4           30.0
47     ed_we              140340000              5               2022                            Welcome to Eden                        welcome to eden                            Welcome to Eden           40.482              7.090            233.0                            Welcome to Eden                 NaN            NaN
48     me_na              138980000              4               2021                             Narcos: Mexico                          narcos mexico                             Narcos: Mexico           47.476              7.939           1160.0                             Narcos: Mexico                 8.3       102053.0
49   af_ki_s              138540000             10               2021                       The King's Affection                   the king s affection                       The King's Affection           69.819              8.351            232.0                       The King's Affection                 8.0         8733.0
50     ju_ju              134560000              7               2022                           Juvenile Justice                       juvenile justice                           Juvenile Justice           14.269              7.947             85.0                           Juvenile Justice                 NaN            NaN
51     81_ar              129470000              3               2022                                 Archive 81                             archive 81                                 Archive 81           20.088              7.219            442.0                                 Archive 81                 7.3        68254.0
52  be_ou_su              128890000              8               2021                         Our Beloved Summer                     our beloved summer                         Our Beloved Summer           30.456              8.500             74.0                         Our Beloved Summer                 8.4          252.0
53     al_so              127690000              8               2022                           Alchemy of Souls                       alchemy of souls                           Alchemy of Souls           61.172              8.622            411.0                           Alchemy of Souls                 8.7        29759.0
54     do_go              112580000              6               2021                            The Good Doctor                        the good doctor                            The Good Doctor          681.614              8.503          11768.0                            The Good Doctor                 NaN            NaN
55  ca_or_sn              112140000              6               2021                 The Snitch Cartel: Origins              the snitch cartel origins                 The Snitch Cartel: Origins           42.083              7.885            283.0                 The Snitch Cartel: Origins                 6.0          321.0
56        si              109430000              2               2021                                   Sintonia                               sintonia                                   Sintonia           22.377              8.200            179.0                                   Sintonia                 NaN            NaN
57     bl_ou              105150000              9               2022                                  Our Blues                              our blues                                  Our Blues           12.980              8.800             43.0                                  Our Blues                 8.6         5554.0
58     fi_ki              104610000              3               2021                                 First Kill                             first kill                                 First Kill           21.147              7.952            270.0                                 First Kill                 NaN            NaN
59     ch_ma              104210000              5               2021                           The Chestnut Man                       the chestnut man                           The Chestnut Man           15.750              7.584            455.0                           The Chestnut Man                 7.6        68351.0

## our analysis
？？